title: "The Happy Valley Latin Festival"
url: https//:happyvalleylatinfestival.github.io

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

# navigation:
#   - title: About
#     url: /index.html
#   - title: Speakers
#     url: /speakers
#   - title: The Symposium
#     url: /symposium

name: 
  en: The Happy Valley Latin Festival
  es: El Festival Latino de Happy Valley
description: 
  en: A language, a feeling, we are family, to the rhythm of the same beat!
  es: ¡Un idioma, un sentir, somos familia, al ritmo de un mismo son!
footer:
  en: Un evento organizado por la comunidad. Multilingual web frame by <a href="http://multilingualdh.org">multilingualdh</a> 
  es: An event organized by the community. Marco web multilingüe de <a href="http://multilingualdh.org">multilingualdh</a>
  
  #can add an image to the footer with <img src="//www.mysite.com/wp-content/uploads/image.jpg" />
exclude: 
- README.md
permalink: pretty
repository: happyvalleylatinfestival/happyvalleylatinfestival.github.io
base-url: ""

social:
  github: happyvalleylatinfestival 
#  instagram: hvlatinfestival
#  facebook: brianmaierjr
#  email: hvlatinfestival@gmail.com

#### google_analytics: "UA-58263416-1" #### what is this? #### 
